info:
  contact: {}
paths:
  /identify-key-words:
    post:
      consumes:
      - application/json
      description: Recebe termos de marca e um email, e retorna links patrocinados
        do Google que usam esses termos.
      parameters:
      - description: Termos de Marca
        in: body
        name: terms
        required: true
        schema:
          type: string
      - description: Email para envio do relatório
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Obrigado! O diagnóstico será processado e enviado para o seu
            email.
          schema:
            type: string
        "400":
          description: Erro na solicitação
          schema:
            type: string
        "500":
          description: Erro no processamento
          schema:
            type: string
      summary: Identifica palavras-chave de concorrentes
swagger: "2.0"
